### ISSUE TITLE
Find/Steal emoji command

### ISSUE THREAD

**Issue by GioGio03** [Sintya4/PREMIUM-DGH-BOT-V2#12]
Hello! There is a serious bug into the find emoji command. If you are at the first page and you click the button **previous** you will get an error and your bot will go off. Hope to get a reply soon
![Screenshot_20211014-213744_Discord](https://user-images.githubusercontent.com/84544068/137384423-014cd22a-1831-4412-9690-8a9ce403b8a7.jpg)

**Comment by Sintya4** [comment]
sorry, we couldn't find the error

**Comment by GioGio03** [comment]
Oh ok but can you do a thing like when we are in the first page the previous button is disabled when we go to the second/third page the button will not disabled anymore

**Comment by Sintya4** [comment]
Uh, what do you mean now?

**Comment by Lcxd65** [comment]
A thing like this, as you can see when you are in the first page the button is disables
https://user-images.githubusercontent.com/84544068/137550892-0712b53d-2de7-4c62-8986-21a0bebc900c.mp4

**Comment by GioGio03** [comment]
https://user-images.githubusercontent.com/84544068/137550971-0961fa6c-b323-41ba-a05a-6a240f9680fa.mp4

As you can see when you are in the first page the button is disabled so can you add that?

**Comment by Sintya4** [comment]
ok i will make it...

**Comment by GioGio03** [comment]
Nice
