### ISSUE TITLE
Credit me atleast

### ISSUE THREAD

**Issue by Rahuletto** [Sintya4/PREMIUM-DGH-BOT-V2#14]
Hello. Rahuletto here. I am the developer of simply-djs. I saw that you have used my rps, tictactoe, embedCreate (embedder) code from my package. But still you haven't credited me. I request you to credit me atleast. Or use my package instead of the code. Because people here use will think it's your own code 

Thanks in regards,
Rahul ;)

**Comment by Sintya4** [comment]
oh sorry, I didn't know that

**Comment by Sintya4** [comment]
Because I got this code on my friend's dc, not from your package

**Comment by Rahuletto** [comment]
Oh ok but it's literally ripped from my package and removed the credits part from the code.

**Comment by breftejk** [comment]
The same issue with discord-dashboard :))

**Comment by Sintya4** [comment]
> The same issue with discord-dashboard :))

Just a slight fix there but the next update doesn't use this anymore!
JOIN MY SERVER IN https://dghbot.ddns.net/dc to ask for help
