### ISSUE TITLE
All the things that doesn't work xD

### ISSUE THREAD

**Issue by Tibe7937** [Sintya4/PREMIUM-DGH-BOT-V2#16]
- Giveaway (slash) the bot doesn't react with any reaction.
- !react command, bot doesn't react with any reaction.
- Backup 'confirm' doesn't do anything
- A lot of fun commands make a error

**Comment by Tibe52** [comment]
Same here

**Comment by Sintya4** [comment]
HELLO, JOIN MY SERVER IN https://dghbot.ddns.net/dc to ask for help
