### ISSUE TITLE
Fix bug sign in to confirm age

### ISSUE THREAD

**Issue by ghost** [Sintya4/PREMIUM-DGH-BOT-V2#2]
Plase fix bug sign in to confirm age 

##My Youtube Link: https://youtu.be/ZrK3U9poJHc

**Comment by Sintya4** [comment]
Please give me a picture I don't understand what you're saying right

**Comment by ManunYaHoo** [comment]
> Please give me a picture I don't understand what you're saying right

![Uploading Screenshot_2021-08-03-21-53-20-224_com.microsoft.rdc.androidx.jpg…]()

**Comment by ghost** [comment]
> Please give me a picture I don't understand what you're saying right

![Screenshot_2021-08-03-21-53-20-224_com microsoft rdc androidx](https://user-images.githubusercontent.com/83857621/128037971-79c44c08-8a91-4403-a08e-3338f6098a83.jpg)
