### ISSUE TITLE
Dashboard problem

### ISSUE THREAD

**Issue by ju52b** [Sintya4/PREMIUM-DGH-BOT-V2#29]
what should i put in the dashboard URL ?
(I use replit and i put the projet dashboard url in the config file but when i went to the site i can't access to Manage Guilds)
When i click on Manage Guilds :
[https://prnt.sc/26sk0e0](url)
What happen :
[https://prnt.sc/26sk0ik](url)

can you help me please i don't know what to do

**Comment by Sintya4** [comment]
HELLO, JOIN MY SERVER IN https://dghbot.ddns.net/dc to ask for help
