### ISSUE TITLE
User is not online yet. retrying

### ISSUE THREAD

**Issue by PratikJena-ops** [Sintya4/PREMIUM-DGH-BOT-V2#35]
I ran that in repl... but it didnt work
![issue](https://user-images.githubusercontent.com/80625019/157646346-e95d1a27-48dc-4abc-8667-9978411ecd46.png)

**Comment by PratikJena-ops** [comment]
@Sintya4 please help!

**Comment by OPM-MASTER** [comment]
> @Sintya4 please help!

yeah, you need to reinstall

```js
npm uninstall discord-yt-poster && npm i discord-yt-poster
```
on the console

**Comment by PratikJena-ops** [comment]
> > @Sintya4 please help!
> 
> yeah, you need to reinstall
> 
> ```js
> npm uninstall discord-yt-poster && npm i discord-yt-poster
> ```
> 
> on the console
> 
> hope it helps

Ty a lot!

**Comment by PratikJena-ops** [comment]
@OPM-MASTER Could you also give me the server invite? because commands in events like music are not working! like can you tell me the commands?

**Comment by Sintya4** [comment]
HELLO, JOIN MY SERVER IN https://dghbot.ddns.net/dc to ask for help
