### ISSUE TITLE
Update DGH BOT V2

### ISSUE THREAD

**Issue by Sintya4** [Sintya4/PREMIUM-DGH-BOT-V2#4]
[✔️]  Add  Slash Command
Hey are you interested in my bot?
Come on, add our bot on your server
Links:

[Invite Me](https://discord.com/api/oauth2/authorize?client_id=849903077690572800&permissions=4232052735&redirect_uri=https%3A%2F%2Fdgh-bot.ddns.net%2Flogin&response_type=code&scope=applications.commands%20bot%20identify%20guilds%20guilds.join)
[Dashboard](https://dgh-bot.ddns.net)
[Vote Me](https://discord4bots.ddns.net/bot/849903077690572800)

[![Vote Me](https://discord4bots.ddns.net/bot/849903077690572800/widget)
](https://discord4bots.ddns.net/bot/849903077690572800)

@Sintya4 
@Khanmanan

**Comment by Khanmanan** [comment]
No need 😒

**Comment by Sintya4** [comment]
> No need

...
