### ISSUE TITLE
Error sign in to confirm age

### ISSUE THREAD

**Issue by ghost** [Sintya4/PREMIUM-DGH-BOT-V2#6]
Link: https://youtu.be/ZrK3U9poJHc

Image

![Screenshot_2021-08-05-22-25-14-564_com microsoft rdc androidx](https://user-images.githubusercontent.com/83857621/128377260-3f31af0d-c0f5-41d9-a25b-c79f25382a26.jpg)

**Comment by Sintya4** [comment]
Error Package ytdl-core
