### ISSUE TITLE
DGH BOT SOON

### ISSUE THREAD

**Issue by Sintya4** [Sintya4/PREMIUM-DGH-BOT-V2#8]
DGH-BOT-V2 WILL UPDATE DISCORD.JS V12 TO DISCORD.JS V13
AND FIX TO COMMAND, LIMIT ERROR TO COMMAND.
***
What New DGH BOT V2 Next?
- [ ] Dashboard (`Soon`)
- [ ] Anti Nuke (`Soon`)
- [ ] Auto Mod (`Soon`)
- [x] Changing All Files.js for Better and Cooler
- [x] Changed the appearance of Embed, other commands.
- [x] Giveaway Req (`Server_id, Roles, Message Count, Reaction Count`) 
- [x] Add Command Fun.
- [x] Add Command Moderation.
- [x] Add Command Games.
- [x] Add Command Stats Server.
- [x] Update System Level V2.
- [x] Update System Server Logs
- [ ] Update Command Welcome-goodbye (`Support With Emojis`).
- [x] Add System Bot Online Logs
- Preview:
![Not my Bot But I will add it 🗿](https://user-images.githubusercontent.com/81017780/129307179-57a6ff12-b9c2-461b-8842-e5244a84f4c2.png)
***
![DGH-BOT.gif](https://user-images.githubusercontent.com/81017780/129313265-1724f409-afa3-40fc-99dd-efba683ca678.gif)

**Comment by Khanmanan** [comment]
Wt?

**Comment by Sintya4** [comment]
> Wt?

Nothing
